##.title
## â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“
##
## ðŸ‡½ðŸ‡¾ðŸ‡¿ & Dev
##
## Licencing details are in the LICENSE file in the root directory.
##
## â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“
##.title~

name: _services
publish_to: none

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.3.1 <4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  flutter:
    sdk: flutter

  _data:
    path: ../_data
  _service_interfaces:
    path: ../_service_interfaces

  xyz_gen_annotations: ^0.21.0
  xyz_pod: ^0.27.0
  xyz_utils: ^0.52.0

  cloud_firestore: ^4.15.9
  firebase_auth: ^4.17.9
  firebase_storage: ^11.6.10
  firebase_core: ^2.27.1
  shared_preferences: ^2.2.2
  meta: any

## -----------------------------------------------------------------------------

dev_dependencies:
  flutter_lints: any
